import { IconCode, IconZap, IconBox, IconGear, IconBrush } from './Icons';

export const members = [
  {
    id: 'antonio',
    name: 'Antônio Pedro',
    role: 'Modelagem 3D',
    description: 'Modelagem 3D, estrutura mecânica e design dos robôs.',
    icon: <IconBox size={30} />,
    color: '#FF8C4A',
    initials: 'A',
    instagram: '@wiik1223',
    image: '/membros/antonio.jpeg',
  },
  {
    id: 'beatriz',
    name: 'Beatriz',
    role: 'Mídia & Design',
    description: 'Mídia, divulgação, identidade visual e produção de conteúdos da equipe.',
    icon: <IconBrush size={30} />,
    color: '#81D4FA',
    initials: 'B',
    instagram: '@beatrizt.sv',
  },
  {
    id: 'bianca',
    name: 'Bianca Muniz',
    role: 'Mídia & Design',
    description: 'Mídia, divulgação, identidade visual e produção de conteúdos da equipe.',
    icon: <IconBrush size={30} />,
    color: '#FF8C4A',
    initials: 'B',
    instagram: '@eu.biancamuniz',
    image: '/membros/Bianca.png',
  },
  {
    id: 'fernanda',
    name: 'Fernanda Santos',
    role: 'Modelagem 3D',
    description: 'Modelagem 3D, estrutura mecânica e design dos robôs.',
    icon: <IconBox size={30} />,
    color: '#81D4FA',
    initials: 'F',
    instagram: '@nanda_fehs2',
    image: '/membros/fernanda.jpeg',
  },
  {
    id: 'ingrid',
    name: 'Ingrid',
    role: 'Eletrônica',
    description: 'Eletrônica dos robôs, montagem elétrica e apoio na integração dos componentes.',
    icon: <IconZap size={30} />,
    color: '#FF8C4A',
    initials: 'I',
    instagram: '@ingrids.nns',
    image: '/membros/ingrid.jpg',
  },
  {
    id: 'nathan',
    name: 'Nathan Maciel',
    role: 'Programação',
    description: 'Programação dos robôs e apoio nas integrações do sistema.',
    icon: <IconCode size={30} />,
    color: '#4FC3F7',
    initials: 'N',
    instagram: '@nathanmaciel5',
    image: '/membros/Nathan.webp',
  },
  {
    id: 'pedro',
    name: 'Pedro Victor',
    role: 'Líder',
    description: 'Apoio geral, organização, integração da equipe e suporte técnico.',
    icon: <IconGear size={30} />,
    color: '#FF8C4A',
    initials: 'P',
    instagram: '@pedro_victor4896',
    image: '/membros/pedro.jpg',
  },
  {
    id: 'victor',
    name: 'Victor Rodrigues',
    role: 'Eletrônica',
    description: 'Eletrônica dos robôs, montagem elétrica e integração dos componentes.',
    icon: <IconZap size={30} />,
    color: '#4FC3F7',
    initials: 'V',
    instagram: '@vii.ctorx',
    image: '/membros/Victor.jpeg',
  },
];
